import type { IconAliases, IconSet } from 'vuetify'
import { VComponentIcon } from 'vuetify/components'

import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowsVertical,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCircleDot,
  IconInfoCircle,
  IconMenu2,
  IconMinus,
  IconPaperclip,
  IconPencil,
  IconPlus,
  IconRefresh,
  IconSortAscending,
  IconSortDescending,
  IconSquare,
  IconSquareCheckFilled,
  IconSquareMinus,
  IconStar,
  IconStarFilled,
  IconStarHalfFilled,
  IconX,
} from '@tabler/icons-vue'

export const tablerIconAliases: IconAliases = {
  collapse: IconChevronUp,
  complete: IconCheck,
  cancel: IconX,
  close: IconX,
  delete: IconX,
  clear: IconX,
  success: IconCircleCheck,
  info: IconInfoCircle,
  warning: IconAlertCircle,
  error: IconAlertTriangle,
  prev: IconChevronLeft,
  next: IconChevronRight,
  checkboxOn: IconSquareCheckFilled,
  checkboxOff: IconSquare,
  checkboxIndeterminate: IconSquareMinus,
  delimiter: IconCircle,
  sortAsc: IconSortAscending,
  sortDesc: IconSortDescending,
  expand: IconChevronDown,
  menu: IconMenu2,
  subgroup: IconChevronDown,
  dropdown: IconChevronDown,
  radioOn: IconCircleDot,
  radioOff: IconCircle,
  edit: IconPencil,
  ratingEmpty: IconStar,
  ratingFull: IconStarFilled,
  ratingHalf: IconStarHalfFilled,
  loading: IconRefresh,
  first: IconChevronsLeft,
  last: IconChevronsRight,
  unfold: IconArrowsVertical,
  file: IconPaperclip,
  plus: IconPlus,
  minus: IconMinus,
  calendar: IconCalendar,
}

export const tablerIconSet: IconSet = {
  component: VComponentIcon,
}
